export const moods = [
  {
    id: "1",
    name: "Happy",
    emoji: "😊",
    color: "#FFD166",
    description: "Upbeat and cheerful tunes to match your happy mood",
    cover: "https://picsum.photos/200?grayscale",
  },
  {
    id: "2",
    name: "Sad",
    emoji: "😢",
    color: "#6E8BFA",
    description: "Comforting songs for when you need a little solace",
    cover: "https://picsum.photos/201?grayscale",
  },
  {
    id: "3",
    name: "Energetic",
    emoji: "⚡",
    color: "#EF476F",
    description: "High-energy tracks to fuel your motivation",
    cover: "https://picsum.photos/202?grayscale",
  },
  {
    id: "4",
    name: "Relaxed",
    emoji: "😌",
    color: "#06D6A0",
    description: "Calm and soothing melodies to unwind with",
    cover: "https://picsum.photos/203?grayscale",
  },
  {
    id: "5",
    name: "Romantic",
    emoji: "❤️",
    color: "#FF6B6B",
    description: "Love songs for those special moments",
    cover: "https://picsum.photos/204?grayscale",
  },
  {
    id: "6",
    name: "Focus",
    emoji: "🧠",
    color: "#A78BFA",
    description: "Music to help you concentrate and be productive",
    cover: "https://picsum.photos/205?grayscale",
  },
];
